allowBuilds:
  esbuild: true
  sharp: true
  workerd: true

# configDependencies:
#   "@pnpm/pacquet": 0.11.12

catalogs:
  dev:
    "@types/node": 26.1.1
    "@typescript/native-preview": 7.0.0-dev.20260707.2
    "@virtual-live-lab/tsconfig": 2.1.23
    typescript: 7.0.2
    vite-plus: 0.2.4
  vivlio:
    "@vivliostyle/cli": "11.0.4"

overrides:
  vite: "npm:@voidzero-dev/vite-plus-core@0.2.4"

patchedDependencies:
  hono@4: patches/hono@4.12.27.patch
